### ISSUE TITLE
Video Link in README not working

### ISSUE THREAD

**Issue by changhsinlee** [amit-sharma/causal-inference-tutorial#1]
Hi Amit, looks like the video was moved elsewhere and stopped working.
* https://mediasite.kellogg.northwestern.edu/Mediasite/Play/8e78dc83c6fb4d20abeeb18028a8f7071d?catalog=1533bdef-0c88-4513-ad97-5fce50c92e62

Any chance that you can update this link in the README? Thanks.

**Comment by anuragreddygv323** [comment]
Please upload the correct link in the Readme file. Its urgent for my Phd.Thanks!

**Comment by chitown88** [comment]
Also looking for that link. I tried to submit a request as well and got no where.

**Comment by iperezr** [comment]
Also looking forward to the video. 
Thank you!

**Comment by amit-sharma** [comment]
Thanks @changhsinlee @anuragreddygv323 @chitown88 @iperezr for your interest. I contacted the Kellogg folks and the video is back up. Here's the updated link (also on the readme):
https://kellogg-northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=7ebafe1f-8af3-46a2-8308-a909014772c0

**Comment by villasv** [comment]
Link is not working again, requires signing in :eyes:
